config/routes.rb
Rails.application.routes.draw do

  resources :consultas
  resources :consultas, except: [:index, :new] do
    resources :signos
    resources :problemas
  end


  match 'consulta/paciente/:paciente_id/index' => 'consultas#index', via: :get, :as => :consulta_index
  match 'consulta/paciente/:paciente_id/new' => 'consultas#new', via: :get, :as => :nueva_consulta
  resources :personas
  resources :alimentos
  resources :suplementos
  resources :pacientes, only: [:index, :new, :create]

  #ruta no acccesible
  match 'pacientes/:id/editar' => 'pacientes#edit', via: :get, :as => :editar_paciente
  match 'pacientes/:id/update' => 'pacientes#update', via: :patch, :as => :update_paciente
  match 'pacientes/:id/eliminar' => 'pacientes#destroy', via: :delete, :as => :eliminar_paciente
  match 'pacientes/:id' => 'pacientes#show', via: :get, :as => :mostrar_paciente

  #quimicas
  match 'paciente/:paciente_id/quimica/new' => 'quimicas#new', via: :get, :as => :new_quimica
  match 'quimicas/create' => 'quimicas#create', via: :post, :as => :create_quimica
  match 'quimicas/:id/update' => 'quimicas#update', via: :patch, :as => :update_quimica
  match 'quimicas/:id/edit' => 'quimicas#edit', via: :get, :as => :edit_quimica
  match 'paciente/:paciente_id/quimicas/index' => 'quimicas#index', via: :get, :as => :index_quimica
  match 'quimica/:id/delete' => 'quimicas#destroy', via: :delete, :as => :eliminar_quimica

  #biometrias
  match 'paciente/:paciente_id/biometria/new' => 'biometrias#new', via: :get, :as => :new_biometria
  match 'biometrias/create' => 'biometrias#create', via: :post, :as => :create_biometria
  match 'biometrias/:id/update' => 'biometrias#update', via: :patch, :as => :update_biometria
  match 'biometrias/:id/edit' => 'biometrias#edit', via: :get, :as => :edit_biometria
  match 'paciente/:paciente_id/biometrias/index' => 'biometrias#index', via: :get, :as => :index_biometria
  match 'biometria/:id/delete' => 'biometrias#destroy', via: :delete, :as => :eliminar_biometria

  #actividades
  match 'paciente/:paciente_id/actividad/new' => 'actividades#new', via: :get, :as => :new_actividad
  match 'actividades/create' => 'actividades#create', via: :post, :as => :create_actividad
  match 'actividades/:id/update' => 'actividades#update', via: :patch, :as => :update_actividad
  match 'actividades/:id/edit' => 'actividades#edit', via: :get, :as => :edit_actividad
  match 'paciente/:paciente_id/actividades/index' => 'actividades#index', via: :get, :as => :index_actividad
  match 'actividad/:id/delete' => 'actividades#destroy', via: :delete, :as => :eliminar_actividad

  #habitos
  match 'paciente/:paciente_id/habitos/new' => 'habitos#new', via: :get, :as => :new_habito
  match 'habitos/create' => 'habitos#create', via: :post, :as => :create_habito
  match 'habitos/:id/update' => 'habitos#update', via: :patch, :as => :update_habito
  match 'habitos/:id/edit' => 'habitos#edit', via: :get, :as => :edit_habito
  match 'paciente/:paciente_id/habitos/index' => 'habitos#index', via: :get, :as => :index_habito
  match 'habito/:id/delete' => 'habitos#destroy', via: :delete, :as => :eliminar_habito

  #antecedentes Clinicos
  match 'paciente/:paciente_id/antecedente/new' => 'antecedentes#new', via: :get, :as => :new_antecedente
  match 'antecedente/create' => 'antecedentes#create', via: :post, :as => :create_antecedente
  match 'antecedente/:id/update' => 'antecedentes#update', via: :patch, :as => :update_antecendete
  match 'antecedente/:id/edit' => 'antecedentes#edit', via: :get, :as => :edit_antecedente
  match 'paciente/:paciente_id/antecedentes/index' => 'antecedentes#index', via: :get, :as => :index_antecedente
  match 'antecedente/:id/delete' => 'antecedentes#destroy', via: :delete, :as => :eliminar_antecedente

  #plan de suplementos
  match 'paciente/:paciente_id/plan_suplementos/new' => 'plansuplementos#new', via: :get, :as => :new_plan
  match 'plan_suplemento/create' => 'plansuplementos#create', via: :post, :as => :create_plan
  match 'plan_suplemento/:id/update' => 'plansuplementos#update', via: :patch, :as => :update_plan
  match 'plan_suplemento/:id/edit' => 'plansuplementos#edit', via: :get, :as => :edit_plan
  match 'paciente/:paciente_id/plan_suplementos/index' => 'plansuplementos#index', via: :get, :as => :index_plan
  match 'plan_suplemento/:id/delete' => 'plansuplementos#destroy', via: :delete, :as => :eliminar_plan

  #dietas
  match 'paciente/:paciente_id/dieta/new' => 'dietas#new', via: :get, :as => :new_dieta
  match 'dieta/create' => 'dietas#create', via: :post, :as => :create_dieta
  match 'dieta/:id/update' => 'dietas#update', via: :patch, :as => :update_dieta
  match 'dieta/:id/edit' => 'dietas#edit', via: :get, :as => :edit_dieta
  match 'paciente/:paciente_id/dietas/index' => 'dietas#index', via: :get, :as => :index_dieta
  match 'dieta/:id/delete' => 'dietas#destroy', via: :delete, :as => :eliminar_dieta


  get 'nutrismart/home'


  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  match 'registrar/nutriologo', to: 'home#registro', via: :post, :as  => :guardar_nutriologo

  get 'login', to: 'sessions#new'
  match 'login' => 'sessions#create', via: :post
  delete 'logout', to: 'sessions#destroy'
  match 'register' => 'sessions#register', via: :get, :as => :registrar_nutriologo

  match 'home/index' => 'home#index', via:  :get, :as => :home_path


  root :to => 'sessions#new'
end

app/models/paciente.rb
class Paciente < ApplicationRecord
  #dependent: :destroy ==== permite destruir al paciente junto con sus datos personales
  has_many :personas, :as => :perstable, dependent: :destroy
  has_many :quimicas
  has_many :biometrias
  has_many :actividades
  has_many :habitos
  has_many :antecedentes
  has_many :plansuplementos
  has_many :dietas


end

app/controllers/pacientes_controller.rb
class PacientesController < ApplicationController
  before_action :require_user
  before_action :set_paciente, only: [:show, :destroy]
  #TODO la parte de update debe corregirse pero mejor continuar con lo que sigue es el unico modulo que no sirve
  #TODO editar datos personales y de paciente pro separado facilita las cosas
  #
  # GET /pacientes
  # GET /pacientes.json
  def index
    #paciente_by_nutriologo = Paciente.where(nutriologo_id: session[:nutriologo_id])
    @pacientes = Persona.paciente
    # Se opto por crear un scope, de esta forma ya se manda a llamar solo esl scope como muestra arriba. el scope esta definido en el modelo
    # persona.perstable <= esto obtiene  el registro que concide con el id seleccionado algo como Paciente.where(id:
  end

  # GET /pacientes/1
  # GET /pacientes/1.json
  def show
    @persona = Persona.find(params[:id])
    @paciente = @persona.perstable
    #aqui deben ir los datos del paciente tambien
  end

  # GET /pacientes/new
  def new
    @paciente = Paciente.new
    @persona = @paciente.personas.new
  end

  # GET /pacientes/1/edit
  def edit
    #Editar solo los datos del paciente como correo.

    @paciente = Paciente.find(params[:id])
    @persona = @paciente.personas.last

  end
  def edit_paciente
  end

  # POST /pacientes
  # POST /pacientes.json
  def create
    @paciente = Paciente.new(paciente_params)
    @persona = @paciente.personas.new(persona_params)

    respond_to do |format|
      if @persona.save
        format.html { redirect_to pacientes_url, notice: 'Datos del paciente fueron guardados' }
      else
        format.html { render :new }
        format.json { render json: @paciente.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /pacientes/1
  # PATCH/PUT /pacientes/1.json
  # falta revisar esta parte
  def update
    @paciente = Paciente.find(params[:id])

    @upersona = @paciente.personas.last
    @paciente_edit = @upersona.perstable
    respond_to do |format|
      if @paciente_edit.update(params[:paciente].permit(:domicilio, :civil, :nss, :edad, :peso, :talla, :imc, :t_sangre, :persona))
        format.html { redirect_to pacientes_path , notice: 'Paciente was successfully updated.' }
        format.json { render :show, status: :ok, location: pacientes_path }
      else
        format.html { render :edit }
        format.json { render json: @paciente.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /pacientes/1
  # DELETE /pacientes/1.json
  def destroy
    #elimina correctamente pero falta pedir confirmacion o validar que se pueda destruir
    @paciente.destroy
    respond_to do |format|
      format.html { redirect_to pacientes_url, notice: 'Paciente Eliminado correctamente.' }
      format.json { head :no_content }
    end
  rescue ActiveRecord::StatementInvalid => e
    flash[:danger] = 'No se puede eliminar el registro esta en uso'
    redirect_to pacientes_path
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_paciente
    @persona = Persona.find(params[:id])
    @paciente = @persona.perstable
  end

  # Only allow a list of trusted parameters through.
  def paciente_params
    params.require(:persona).require(:paciente).permit(:domicilio, :civil, :nss, :edad, :peso, :talla, :imc, :t_sangre, :nutriologo_id)
  end
  def persona_params
    params.require(:persona).permit(:nombre,:paterno,:materno,:sexo, :telefono, :correo)

  end
end

app/helpers/pacientes_helper.rb
module PacientesHelper
end

app/views/pacientes/_datos_paciente.html.erb
<p>
  <strong>Nombre:</strong>
  <%= @persona.nombre %>
</p>

<p>
  <strong>Paterno:</strong>
  <%= @persona.paterno %>
</p>

<p>
  <strong>Materno:</strong>
  <%= @persona.materno %>
</p>

<p>
  <strong>Sexo:</strong>
  <%= @persona.sexo %>
</p>

<p>
  <strong>Telefono:</strong>
  <%= @persona.telefono %>
</p>

<p>
  <strong>Domicilio:</strong>
  <%= @paciente.domicilio %>
</p>

<p>
  <strong>Civil:</strong>
  <%= @paciente.civil %>
</p>

<p>
  <strong>Nss:</strong>
  <%= @paciente.nss %>
</p>

<p>
  <strong>Edad:</strong>
  <%= @paciente.edad %>
</p>

<p>
  <strong>Peso:</strong>
  <%= @paciente.peso %>
</p>

<p>
  <strong>Talla:</strong>
  <%= @paciente.talla %>
</p>

<p>
  <strong>Imc:</strong>
  <%= @paciente.imc %>
</p>

<p>
  <strong>T sangre:</strong>
  <%= @paciente.t_sangre %>
</p>

app/views/pacientes/_form.html.erb
<%= form_with(model: @persona, id: 'formulario_pacientes', url: url, local: true) do |persona| %>

  <div class="form-group">
    <%= persona.text_field :nombre, placeholder: "Introduzaca su Nombre"%>
  </div>

  <div class="form-group">
    <%= persona.text_field :paterno, placeholder: "Paterno"%>
  </div>

  <div class="form-group">
    <%= persona.text_field :materno, placeholder: "Materno"%>
  </div>

  <div class="form-group">
    <%= persona.label :sexo%><br>
    <%= persona.select :sexo, options_for_select([["Seleccione uno",nil], %w[Hombre H], %w[Mujer M], %w[Otro O]])%>
  </div>

  <div class="form-group">
    <%= persona.telephone_field(:telefono, placeholder: "telefono")%>
  </div>

  <div class="form-group">
    <%= persona.email_field(:correo, placeholder: "correo") %>
  </div>
  <%= persona.fields_for :paciente do |paciente_fields| %>

    <div class="form-group">
      <%= paciente_fields.text_field :domicilio ,placeholder: "domicilio"%>
    </div>

    <div class="form-group">
      <%= paciente_fields.label "Estado civil" %><br>
      <%= paciente_fields.select :civil,options_for_select([["Seleccione uno", nil], %w[Soltero Soltero], %w[Casado Casado], %w[Divorciado Divorciado]]) %>
    </div>

    <div class="form-group">
      <%= paciente_fields.label "Numero de Seguro Social" %><br>
      <%= paciente_fields.text_field :nss , placeholder: "NSS"%>
    </div>

    <div class="form-group">
      <%= paciente_fields.number_field :edad, placeholder: "Edad"%>
    </div>

    <div class="form-group">
      <%= paciente_fields.text_field :peso, placeholder: "Peso en Kg" %>
    </div>

    <div class="form-group">
      <%= paciente_fields.label "Estatura en cm"%><br>
      <%= paciente_fields.text_field :talla, placeholder: "Estatura en cm ex: 170" %>
    </div>

    <div class="form-group">
      <%= paciente_fields.label "Indice de masa corporal:"%><br>
      <%= paciente_fields.number_field :imc %>
    </div>

    <div class="form-group">
      <%= paciente_fields.label "Tipo de sangre"%><br>
      <%= paciente_fields.select :t_sangre, options_for_select([["Seleccione uno",nil], ["O negrativo","O negativo"],
                                                                ["O positivo","O positivo"],["A negativo","A negativo"], ["A positivo","A positivo"],
                                                                ["B negativo","B negativo"], ["B positivo","B positivo"], ["AB negativo","AB negativo"],
                                                                ["AB positivo","AB positivo"]])%>
    </div>
    <%= paciente_fields.hidden_field(:nutriologo_id, :value => session[:nutriologo_id]) %>
  <% end %>
  <br>
  <div class="actions">
    <%= persona.submit 'Crear', class: 'btn btn-primary'%>

  </div>
<% end %>

app/views/pacientes/edit.html.erb
<h1> Editar Paciente</h1>
<%= form_with(model: @persona, id: 'formulario_pacientes', url: persona_path, local: true) do |persona| %>
  <div class="form-group">
    Nombre<br>
    <%= persona.text_field :nombre, placeholder: "Introduzaca su Nombre"%>
  </div>

  <div class="form-group">
    Apellido Paterno<br>
    <%= persona.text_field :paterno, placeholder: "Paterno"%>
  </div>

  <div class="form-group">
    Apellido Materno<br>
    <%= persona.text_field :materno, placeholder: "Materno"%>
  </div>

  <div class="form-group">
    <%= persona.label :sexo%><br>
    <%= persona.select :sexo, options_for_select([ %w[Hombre H], %w[Mujer M], %w[Otro O]], :selected => @persona.sexo)%>
  </div>

  <div class="form-group">
    Telefono<br>
    <%= persona.telephone_field(:telefono, placeholder: "telefono")%>
  </div>

  <div class="form-group">
    Correo<br>
    <%= persona.email_field(:correo, placeholder: "correo") %>
  </div>
  <%= persona.fields_for @paciente do |paciente_fields| %>

    <div class="form-group">
      Domicilio<br>
      <%= paciente_fields.text_field :domicilio ,placeholder: "domicilio"%>
    </div>

    <div class="form-group">
      <%= paciente_fields.label "Estado civil" %><br>
      <%= paciente_fields.select :civil,options_for_select([ %w[Soltero Soltero], %w[Casado Casado], %w[Divorciado Divorciado]], :selected =>  @paciente.civil) %>
    </div>

    <div class="form-group">
      <%= paciente_fields.label "Numero de Seguro Social" %><br>
      <%= paciente_fields.text_field :nss , placeholder: "NSS"%>
    </div>

    <div class="form-group">
      Edad<br>
      <%= paciente_fields.number_field :edad, placeholder: "Edad"%>
    </div>

    <div class="form-group">
      Peso en Kg<br>
      <%= paciente_fields.text_field :peso, placeholder: "Peso en Kg" %>
    </div>

    <div class="form-group">
      <%= paciente_fields.label "Estatura en cm"%><br>
      <%= paciente_fields.text_field :talla, placeholder: "Estatura en cm ex: 170" %>
    </div>

    <div class="form-group">
      <%= paciente_fields.label "Indice de masa corporal:"%><br>
      <%= paciente_fields.number_field :imc %>
    </div>

    <div class="form-group">
      <%= paciente_fields.label "Tipo de sangre"%><br>
      <%= paciente_fields.select :t_sangre, options_for_select([["O negrativo","O negativo"],
                                                                ["O positivo","O positivo"],["A negativo","A negativo"], ["A positivo","A positivo"],
                                                                ["B negativo","B negativo"], ["B positivo","B positivo"], ["AB negativo","AB negativo"],
                                                                ["AB positivo","AB positivo"]],:selected => @paciente.t_sangre )%>
    </div>
    <%= paciente_fields.hidden_field(:nutriologo_id, :value => session[:nutriologo_id]) %>
  <% end %>
  <br>
  <div class="actions">
    <%= persona.submit 'Guardar', class: 'btn btn-primary'%>

  </div>
<% end %>

<%= link_to 'Volver', mostrar_paciente_path(@persona.id) %>

app/views/pacientes/index.html.erb
<p id="notice"><%= notice %></p>

<h1 class="h3 mb-2 text-gray-800">Pacientes</h1>

<div class="card shadow mb-4">
  <div class="card-header py3">
    <h6 class="m-0 font-weight-bold text-primary">Informacion de Pacientes</h6>
  </div>

  <div class="card-body">
    <div class="table-responsive">
      <table class="responsive nowrap table table-hover" id="dttb-pacientes" data-sort="true" data-source="<%= url_for(format: :json)%>": >
        <thead>
        <tr>
          <th data-data="nombre">Nombre</th>
          <th data-data="paterno">Paterno</th>
          <th data-data="materno">Materno</th>
          <th data-data="sexo">Sexo</th>
          <th data-data="telefono">Telefono</th>
          <th data-data="url" data-orderable="false" data-class-name="all" data-searchable="false" class="skip-export" width="100px">Acciones</th>
        </tr>
        <thead>

      </table>
    </div>
  </div>

  <%= link_to 'Nuevo Paciente', new_paciente_path, class: 'btn btn-primary btn-icon-split btn-lg' %>

</div>
<br>

app/views/pacientes/new.html.erb
<h1>Nuevo Paciente</h1>

<%= render 'form', paciente: @paciente, url: pacientes_path %>

<%= link_to 'Regresar', pacientes_path , class: 'btn btn-success'%>

app/views/pacientes/show.html.erb
<p id="notice"><%= notice %></p>
<div class="row">
  <div class="col-lg-6">

    <div class="card shadow mb-4">
      <div class="card-header py-3">
        <h6 class="m-0 font-weight-bold text-primary">Datos del paciente</h6>
      </div>
      <div class="card-body">
        <%= render 'datos_paciente' %>

        <%= link_to 'Editar o actualizar datos Personales', editar_paciente_path(@paciente.id), class: "btn btn-info" %> |
        <%= link_to 'Volver', pacientes_path, class: "btn btn-success"%>

      </div>
    </div>


  </div>
  <div class="col-lg-6">

    <div class="card shadow mb-4">
      <div class="card-header py-3">
        <h6 class="m-0 font-weight-bold text-primary">Datos de Control</h6>
        <br>
      </div>
      <div class="card-body">
        <%= link_to 'Quimicas Sanguinea', index_quimica_path(@paciente.id), class: 'btn btn-primary w-100'  %>
        <br>
        <br>
        <%= link_to 'Biometrias Hematica', index_biometria_path(@paciente.id), class: 'btn btn-primary w-100'  %>
        <br>
        <br>
        <%= link_to 'Habitos de Salud', index_habito_path(@paciente.id), class: 'btn btn-primary w-100'  %>
        <br>
        <br>
        <%= link_to 'Actividad Fisica', index_actividad_path(@paciente.id), class: 'btn btn-primary w-100'  %>
        <br>
        <br>
        <%= link_to 'Antecedentes Clinicos', index_antecedente_path(@paciente.id), class: 'btn btn-primary w-100 '  %>
        <br>
        <br>
        <%= link_to 'Plan de suplementos', index_plan_path(@paciente.id), class: 'btn btn-primary w-100 '  %>
        <br>
        <br>
        <%= link_to 'Dieta', index_dieta_path(@paciente.id), class: 'btn btn-primary w-100 '  %>
        <br>
        <br>
        <%= link_to 'Consulta', consulta_index_path(@paciente.id), class: 'btn btn-primary w-100 '  %>
      </div>
    </div>

  </div>
</div>