config/routes.rb
Rails.application.routes.draw do

  resources :consultas
  resources :consultas, except: [:index, :new] do
    resources :signos
    resources :problemas
  end


  match 'consulta/paciente/:paciente_id/index' => 'consultas#index', via: :get, :as => :consulta_index
  match 'consulta/paciente/:paciente_id/new' => 'consultas#new', via: :get, :as => :nueva_consulta
  resources :personas
  resources :alimentos
  resources :suplementos
  resources :pacientes, only: [:index, :new, :create]

  #ruta no acccesible
  match 'pacientes/:id/editar' => 'pacientes#edit', via: :get, :as => :editar_paciente
  match 'pacientes/:id/update' => 'pacientes#update', via: :patch, :as => :update_paciente
  match 'pacientes/:id/eliminar' => 'pacientes#destroy', via: :delete, :as => :eliminar_paciente
  match 'pacientes/:id' => 'pacientes#show', via: :get, :as => :mostrar_paciente

  #quimicas
  match 'paciente/:paciente_id/quimica/new' => 'quimicas#new', via: :get, :as => :new_quimica
  match 'quimicas/create' => 'quimicas#create', via: :post, :as => :create_quimica
  match 'quimicas/:id/update' => 'quimicas#update', via: :patch, :as => :update_quimica
  match 'quimicas/:id/edit' => 'quimicas#edit', via: :get, :as => :edit_quimica
  match 'paciente/:paciente_id/quimicas/index' => 'quimicas#index', via: :get, :as => :index_quimica
  match 'quimica/:id/delete' => 'quimicas#destroy', via: :delete, :as => :eliminar_quimica

  #biometrias
  match 'paciente/:paciente_id/biometria/new' => 'biometrias#new', via: :get, :as => :new_biometria
  match 'biometrias/create' => 'biometrias#create', via: :post, :as => :create_biometria
  match 'biometrias/:id/update' => 'biometrias#update', via: :patch, :as => :update_biometria
  match 'biometrias/:id/edit' => 'biometrias#edit', via: :get, :as => :edit_biometria
  match 'paciente/:paciente_id/biometrias/index' => 'biometrias#index', via: :get, :as => :index_biometria
  match 'biometria/:id/delete' => 'biometrias#destroy', via: :delete, :as => :eliminar_biometria

  #actividades
  match 'paciente/:paciente_id/actividad/new' => 'actividades#new', via: :get, :as => :new_actividad
  match 'actividades/create' => 'actividades#create', via: :post, :as => :create_actividad
  match 'actividades/:id/update' => 'actividades#update', via: :patch, :as => :update_actividad
  match 'actividades/:id/edit' => 'actividades#edit', via: :get, :as => :edit_actividad
  match 'paciente/:paciente_id/actividades/index' => 'actividades#index', via: :get, :as => :index_actividad
  match 'actividad/:id/delete' => 'actividades#destroy', via: :delete, :as => :eliminar_actividad

  #habitos
  match 'paciente/:paciente_id/habitos/new' => 'habitos#new', via: :get, :as => :new_habito
  match 'habitos/create' => 'habitos#create', via: :post, :as => :create_habito
  match 'habitos/:id/update' => 'habitos#update', via: :patch, :as => :update_habito
  match 'habitos/:id/edit' => 'habitos#edit', via: :get, :as => :edit_habito
  match 'paciente/:paciente_id/habitos/index' => 'habitos#index', via: :get, :as => :index_habito
  match 'habito/:id/delete' => 'habitos#destroy', via: :delete, :as => :eliminar_habito

  #antecedentes Clinicos
  match 'paciente/:paciente_id/antecedente/new' => 'antecedentes#new', via: :get, :as => :new_antecedente
  match 'antecedente/create' => 'antecedentes#create', via: :post, :as => :create_antecedente
  match 'antecedente/:id/update' => 'antecedentes#update', via: :patch, :as => :update_antecendete
  match 'antecedente/:id/edit' => 'antecedentes#edit', via: :get, :as => :edit_antecedente
  match 'paciente/:paciente_id/antecedentes/index' => 'antecedentes#index', via: :get, :as => :index_antecedente
  match 'antecedente/:id/delete' => 'antecedentes#destroy', via: :delete, :as => :eliminar_antecedente

  #plan de suplementos
  match 'paciente/:paciente_id/plan_suplementos/new' => 'plansuplementos#new', via: :get, :as => :new_plan
  match 'plan_suplemento/create' => 'plansuplementos#create', via: :post, :as => :create_plan
  match 'plan_suplemento/:id/update' => 'plansuplementos#update', via: :patch, :as => :update_plan
  match 'plan_suplemento/:id/edit' => 'plansuplementos#edit', via: :get, :as => :edit_plan
  match 'paciente/:paciente_id/plan_suplementos/index' => 'plansuplementos#index', via: :get, :as => :index_plan
  match 'plan_suplemento/:id/delete' => 'plansuplementos#destroy', via: :delete, :as => :eliminar_plan

  #dietas
  match 'paciente/:paciente_id/dieta/new' => 'dietas#new', via: :get, :as => :new_dieta
  match 'dieta/create' => 'dietas#create', via: :post, :as => :create_dieta
  match 'dieta/:id/update' => 'dietas#update', via: :patch, :as => :update_dieta
  match 'dieta/:id/edit' => 'dietas#edit', via: :get, :as => :edit_dieta
  match 'paciente/:paciente_id/dietas/index' => 'dietas#index', via: :get, :as => :index_dieta
  match 'dieta/:id/delete' => 'dietas#destroy', via: :delete, :as => :eliminar_dieta


  get 'nutrismart/home'


  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  match 'registrar/nutriologo', to: 'home#registro', via: :post, :as  => :guardar_nutriologo

  get 'login', to: 'sessions#new'
  match 'login' => 'sessions#create', via: :post
  delete 'logout', to: 'sessions#destroy'
  match 'register' => 'sessions#register', via: :get, :as => :registrar_nutriologo

  match 'home/index' => 'home#index', via:  :get, :as => :home_path


  root :to => 'sessions#new'
end

app/models/dieta.rb
class Dieta<ApplicationRecord
  belongs_to :paciente
  belongs_to :alimento
end

app/controllers/dietas_controller.rb
class DietasController < ApplicationController
  before_action :set_dieta, only: [:show, :edit, :update, :destroy]

  # GET /dietas
  # GET /dietas.json
  def index
    set_persona_dieta
  end

  # GET /dietas/1
  # GET /dietas/1.json
  def show
    set_persona_dieta
  end

  # GET /dietas/new
  def new
    @dieta = Dieta.new
    @paciente = Paciente.find(params[:paciente_id])
  end

  # GET /dietas/1/edit
  def edit
  end

  # POST /dietas
  # POST /dietas.json
  def create
    @dieta = Dieta.new(dieta_params)
    respond_to do |format|
      if @dieta.save
        format.html { redirect_to index_dieta_path(params[:dieta][:paciente_id]),
                                  notice: 'Datos guardados correctamente.' }
      else
        format.html { redirect_to index_dieta_path(params[:dieta][:paciente_id]),
                                  notice: 'Ocurrio un error mientras se guardaban los datos.' }
      end
    end
  end

  # PATCH/PUT /dietas/1
  # PATCH/PUT /dietas/1.json
  def update
    respond_to do |format|
      if @dieta.update(dieta_params)
        format.html { redirect_to index_dieta_path(params[:dieta][:paciente_id]),
                                  notice: 'Datos guardados correctamente.' }
      else
        format.html { redirect_to index_dieta_path(params[:dieta][:paciente_id]),
                                  notice: 'Ocurrio un error mientras se guardaban los datos.' }
      end
    end
  end

  # DELETE /dietas/1
  # DELETE /dietas/1.json
  def destroy
    @dieta.destroy
    respond_to do |format|
      format.html { redirect_to index_dieta_path(params[:paciente_id]),
                                notice: 'El registro se elimino correctamente.' }
    end
  end

  private
  def set_persona_dieta
    paciente = Paciente.find(params[:paciente_id])
    @persona = paciente.personas.last
    @dietas = Dieta.where(paciente_id: params[:paciente_id])
  end
  # Use callbacks to share common setup or constraints between actions.
  def set_dieta
    @dieta = Dieta.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def dieta_params
    params.require(:dieta).permit(:paciente_id, :alimento_id, :comida)
  end
end

app/helpers/dietas_helper.rb
module DietasHelper
end

app/views/dietas/_form.html.erb
<%= form_with(model: dieta, id: 'formulario_dieta', url: url, local: true) do |dieta| %>
  <%= dieta.hidden_field(:paciente_id, :value => params[:paciente_id]) %>
  <% #form.collection_select :alimento_id, Alimento.order(:nombre), :id, :nombre, include_blank: true %>
  <div class="form-group">
    <%= dieta.label 'Alimento' %><br>
    <%= dieta.collection_select :alimento_id, Alimento.order(:nombre), :id, :nombre, include_blank: true %>
  </div>
  <div class="form-group">
    <%= dieta.label 'Comida' %><br>
    <div class="row">
      <div class="col-2">
        <%= dieta.radio_button :comida,1, :checked => true%>Desayuno
      </div>
      <div class="col-2">
        <%= dieta.radio_button :comida,2%>Colacion
      </div>
      <div class="col-2">
        <%= dieta.radio_button :comida,3%>Comida
      </div>
      <div class="col-2">
        <%= dieta.radio_button :comida,4%>Cena
      </div>
    </div>
  </div>
  <div class="actions">
    <%= dieta.submit 'Guardar', class: 'btn btn-primary' %>
  </div>
<% end %>

app/views/dietas/edit.html.erb
<h1>Editar Dieta</h1>
<%= render 'form', dieta: @dieta, url: update_dieta_path %>
<br>
<%= link_to 'Regresar', index_dieta_path(params[:paciente_id]), class: 'btn btn-info' %>

app/views/dietas/index.html.erb
<p id="notice"><%= notice %></p>
<%
  paciente = Paciente.find(params[:paciente_id])
  @persona = paciente.personas.last
%>
<p>Nombre del Paciente: <%=  @persona.full_name%> </p>
<hr>
<div class="col-md-6">
  <% @dietas.each do |dieta| %>
    <table class="table table-bordered">
      <tr>
        <th>Alimento </th>
        <td><%= dieta.alimento.nombre%></td>
      </tr>
      <tr>
        <th>Comida</th>
        <% if dieta.comida == 1 %>
          <td>Desayuno</td>
        <% elsif dieta.comida == 2 %>
          <td>Colacion</td>
        <% elsif dieta.comida == 3 %>
          <td>Comida</td>
        <% elsif dieta.comida == 4 %>
          <td>Cena</td>
        <% end %>
      </tr>
      <tr>
        <th><%= link_to 'Editar', edit_dieta_path(dieta.id,paciente_id: dieta.paciente_id),class: 'btn btn-primary' %></th>
      </tr>
      <tr>
        <th><%= link_to 'Eliminar', eliminar_dieta_path(dieta.id,paciente_id: dieta.paciente_id), method: :delete, data: { confirm: 'Estas Seguro'}, class: 'btn btn-danger' %></th>
      </tr>
    </table>
    <hr>
  <% end %>
</div>
<% #TODO Se desactiva el boton %>
<%= link_to 'Agregar Registro', new_dieta_path(params[:paciente_id]), class: 'btn btn-primary' %>
<%= link_to "Volver", mostrar_paciente_path(@persona.id) , class: 'btn btn-success'%>

app/views/dietas/new.html.erb
<h1>Registrar Dieta</h1>
<%= render 'form', dieta: @dieta, url: create_dieta_path %>
<br>
<%= link_to 'Regresar', index_dieta_path(params[:paciente_id]), class: 'btn btn-info' %>