config/routes.rb
Rails.application.routes.draw do

  resources :consultas
  resources :consultas, except: [:index, :new] do
    resources :signos
    resources :problemas
  end


  match 'consulta/paciente/:paciente_id/index' => 'consultas#index', via: :get, :as => :consulta_index
  match 'consulta/paciente/:paciente_id/new' => 'consultas#new', via: :get, :as => :nueva_consulta
  resources :personas
  resources :alimentos
  resources :suplementos
  resources :pacientes, only: [:index, :new, :create]

  #ruta no acccesible
  match 'pacientes/:id/editar' => 'pacientes#edit', via: :get, :as => :editar_paciente
  match 'pacientes/:id/update' => 'pacientes#update', via: :patch, :as => :update_paciente
  match 'pacientes/:id/eliminar' => 'pacientes#destroy', via: :delete, :as => :eliminar_paciente
  match 'pacientes/:id' => 'pacientes#show', via: :get, :as => :mostrar_paciente

  #quimicas
  match 'paciente/:paciente_id/quimica/new' => 'quimicas#new', via: :get, :as => :new_quimica
  match 'quimicas/create' => 'quimicas#create', via: :post, :as => :create_quimica
  match 'quimicas/:id/update' => 'quimicas#update', via: :patch, :as => :update_quimica
  match 'quimicas/:id/edit' => 'quimicas#edit', via: :get, :as => :edit_quimica
  match 'paciente/:paciente_id/quimicas/index' => 'quimicas#index', via: :get, :as => :index_quimica
  match 'quimica/:id/delete' => 'quimicas#destroy', via: :delete, :as => :eliminar_quimica

  #biometrias
  match 'paciente/:paciente_id/biometria/new' => 'biometrias#new', via: :get, :as => :new_biometria
  match 'biometrias/create' => 'biometrias#create', via: :post, :as => :create_biometria
  match 'biometrias/:id/update' => 'biometrias#update', via: :patch, :as => :update_biometria
  match 'biometrias/:id/edit' => 'biometrias#edit', via: :get, :as => :edit_biometria
  match 'paciente/:paciente_id/biometrias/index' => 'biometrias#index', via: :get, :as => :index_biometria
  match 'biometria/:id/delete' => 'biometrias#destroy', via: :delete, :as => :eliminar_biometria

  #actividades
  match 'paciente/:paciente_id/actividad/new' => 'actividades#new', via: :get, :as => :new_actividad
  match 'actividades/create' => 'actividades#create', via: :post, :as => :create_actividad
  match 'actividades/:id/update' => 'actividades#update', via: :patch, :as => :update_actividad
  match 'actividades/:id/edit' => 'actividades#edit', via: :get, :as => :edit_actividad
  match 'paciente/:paciente_id/actividades/index' => 'actividades#index', via: :get, :as => :index_actividad
  match 'actividad/:id/delete' => 'actividades#destroy', via: :delete, :as => :eliminar_actividad

  #habitos
  match 'paciente/:paciente_id/habitos/new' => 'habitos#new', via: :get, :as => :new_habito
  match 'habitos/create' => 'habitos#create', via: :post, :as => :create_habito
  match 'habitos/:id/update' => 'habitos#update', via: :patch, :as => :update_habito
  match 'habitos/:id/edit' => 'habitos#edit', via: :get, :as => :edit_habito
  match 'paciente/:paciente_id/habitos/index' => 'habitos#index', via: :get, :as => :index_habito
  match 'habito/:id/delete' => 'habitos#destroy', via: :delete, :as => :eliminar_habito

  #antecedentes Clinicos
  match 'paciente/:paciente_id/antecedente/new' => 'antecedentes#new', via: :get, :as => :new_antecedente
  match 'antecedente/create' => 'antecedentes#create', via: :post, :as => :create_antecedente
  match 'antecedente/:id/update' => 'antecedentes#update', via: :patch, :as => :update_antecendete
  match 'antecedente/:id/edit' => 'antecedentes#edit', via: :get, :as => :edit_antecedente
  match 'paciente/:paciente_id/antecedentes/index' => 'antecedentes#index', via: :get, :as => :index_antecedente
  match 'antecedente/:id/delete' => 'antecedentes#destroy', via: :delete, :as => :eliminar_antecedente

  #plan de suplementos
  match 'paciente/:paciente_id/plan_suplementos/new' => 'plansuplementos#new', via: :get, :as => :new_plan
  match 'plan_suplemento/create' => 'plansuplementos#create', via: :post, :as => :create_plan
  match 'plan_suplemento/:id/update' => 'plansuplementos#update', via: :patch, :as => :update_plan
  match 'plan_suplemento/:id/edit' => 'plansuplementos#edit', via: :get, :as => :edit_plan
  match 'paciente/:paciente_id/plan_suplementos/index' => 'plansuplementos#index', via: :get, :as => :index_plan
  match 'plan_suplemento/:id/delete' => 'plansuplementos#destroy', via: :delete, :as => :eliminar_plan

  #dietas
  match 'paciente/:paciente_id/dieta/new' => 'dietas#new', via: :get, :as => :new_dieta
  match 'dieta/create' => 'dietas#create', via: :post, :as => :create_dieta
  match 'dieta/:id/update' => 'dietas#update', via: :patch, :as => :update_dieta
  match 'dieta/:id/edit' => 'dietas#edit', via: :get, :as => :edit_dieta
  match 'paciente/:paciente_id/dietas/index' => 'dietas#index', via: :get, :as => :index_dieta
  match 'dieta/:id/delete' => 'dietas#destroy', via: :delete, :as => :eliminar_dieta


  get 'nutrismart/home'


  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  match 'registrar/nutriologo', to: 'home#registro', via: :post, :as  => :guardar_nutriologo

  get 'login', to: 'sessions#new'
  match 'login' => 'sessions#create', via: :post
  delete 'logout', to: 'sessions#destroy'
  match 'register' => 'sessions#register', via: :get, :as => :registrar_nutriologo

  match 'home/index' => 'home#index', via:  :get, :as => :home_path


  root :to => 'sessions#new'
end

app/controllers/actividades_controller.rb
class ActividadesController < ApplicationController
  before_action :set_actividad, only: [:show, :edit, :update, :destroy]

  # GET /actividades
  # GET /actividades.json
  def index
    set_persona_actividad
  end

  # GET /actividades/1
  # GET /actividades/1.json
  def show
    set_persona_actividad
  end

  # GET /actividades/new
  def new
    @actividad = Actividad.new
    @paciente = Paciente.find(params[:paciente_id])
  end

  # GET /actividades/1/edit
  def edit
  end

  # POST /actividades
  # POST /actividades.json
  def create
    @actividad = Actividad.new(actividad_params)

    respond_to do |format|
      if @actividad.save
        format.html { redirect_to index_actividad_path(params[:actividad][:paciente_id]),
                                  notice: 'Datos de Actividad Fisica guardados correctamente.' }
      else
        format.html { redirect_to index_actividad_path(params[:actividad][:paciente_id]),
                                  notice: 'Ocurrio un error mientras se guardaba el registro' }
      end
    end
  end

  # PATCH/PUT /actividades/1
  # PATCH/PUT /actividades/1.json
  def update
    respond_to do |format|
      if @actividad.update(actividad_params)
        format.html { redirect_to index_actividad_path(params[:actividad][:paciente_id]),
                                  notice: 'Actividad se actualizo correctamente.' }
      else
        format.html { redirect_to index_actividad_path(params[:actividad][:paciente_id]),
                                  notice: 'Ocurrio un error mientras se guardaba el registro.' }
      end
    end
  end

  # DELETE /actividades/1
  # DELETE /actividades/1.json
  def destroy
    @actividad.destroy
    respond_to do |format|
      format.html { redirect_to index_actividad_path(params[:paciente_id]),
                                notice: 'Actividad se elimino correctamente.' }
    end
  end

  private

  def set_persona_actividad
    paciente = Paciente.find(params[:paciente_id])
    @persona = paciente.personas.last
    @actividades = Actividad.where(paciente_id: params[:paciente_id])
  end

  # Use callbacks to share common setup or constraints between actions.
  def set_actividad
    @actividad = Actividad.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def actividad_params
    params.require(:actividad).permit(:paciente_id, :deporte, :descripcion, :frecuencia, :duracion,
                                      :tiempo_practica, :grupo_solitario, :equipo_amateur, :gym )
  end
end

app/helpers/actividades_helper.rb
module ActividadesHelper
end

app/views/actividades/_form.html.erb
<%= form_with(model: actividad, id: 'formulario_actividad', url: url, local: true) do |actividad|%>
  <%= actividad.hidden_field(:paciente_id, :value => params[:paciente_id]) %>
  <div class="form-group">
    <%= actividad.label "Practica algun de porte?" %><br>
    <%= actividad.radio_button :deporte, 'No', :checked => true %> No
    <%= actividad.radio_button :deporte, 'Si' %> Si
  </div>
  <div class="form-group">
    <%= actividad.label "Descripcion" %><br>
    <%= actividad.text_area(:descripcion, cols: 40) %>
  </div>
  <div class="form-group ">
    <%= actividad.label "Cuantas veces a la semana lo practica?" %><br>
    <div class="row">
      <div class="col-2">
        <%= actividad.radio_button :frecuencia, 0, :checked => true%>No Practica
      </div>
      <div class="col-2">
        <%= actividad.radio_button :frecuencia,1%>1
      </div>
      <div class="col-2">
        <%= actividad.radio_button :frecuencia,2%>2
      </div>
      <div class="col-2">
        <%= actividad.radio_button :frecuencia,3%>3
      </div>
      <div class="col-2">
        <%= actividad.radio_button :frecuencia,4%>4
      </div>
      <div class="col-2">
        <%= actividad.radio_button :frecuencia,5%>5
      </div>
    </div>
  </div>
  <div class="form-group">
    <%= actividad.label "Si el paciente realiza ejercicio, Cuantas horas?" %><br>
    <div class="row">
      <div class="col-2">
        <%= actividad.radio_button :duracion, 0, :checked => true%>No practica
      </div>
      <div class="col-2">
        <%= actividad.radio_button :duracion,1%>1 hora
      </div>
      <div class="col-2">
        <%= actividad.radio_button :duracion,2%>2 hora
      </div>
      <div class="col-2">
        <%= actividad.radio_button :duracion,3%>Mas de 2 horas
      </div>
    </div>
  </div>
  <div class="form-group">
    <%= actividad.label "Cuanto tiempo lleva ejercitandose?"%><br>
    <div class="row">
      <div class="col-3">
        <%= actividad.radio_button :tiempo_practica,'No se ejercita' , :checked => true%>No se ejercita
      </div>
      <div class="col-3">
        <%= actividad.radio_button :tiempo_practica,'Menos de una semana' %>Menos de una semana
      </div>
      <div class="col-3">
        <%= actividad.radio_button :tiempo_practica,'Entre una semana y un mes'%>Entre una semana y un mes
      </div>
      <div class="col-3">
        <%= actividad.radio_button :tiempo_practica,'Entre un mes y seis meses'%>Entre un mes y seis meses
      </div>
      <div class="col-3">
        <%= actividad.radio_button :tiempo_practica,'Mas de seis Meses'%>Mas de seis Meses
      </div>
    </div>
  </div>
  <div class="form-group">
    <%= actividad.label "Lo practica solo o en grupo?" %><br>
    <div class="row">
      <div class="col-3">
        <%= actividad.radio_button :grupo_solitario, 'Solo', :checked => true%>Solo
      </div>
      <div class="col-3">
        <%= actividad.radio_button :grupo_solitario,'En grupo'%>En grupo
      </div>
    </div>
  </div>
  <div class="form-group">
    <%= actividad.label "Es parte de un equipo?" %><br>
    <div class="row">
      <div class="col-3">
        <%= actividad.radio_button :equipo_amateur, 'No', :checked => true%>No
      </div>
      <div class="col-3">
        <%= actividad.radio_button :equipo_amateur,'Si'%>Si
      </div>
    </div>
  </div>
  <div class="form-group">
    <%= actividad.label "Asiste al gimnasio?" %><br>
    <div class="row">
      <div class="col-3">
        <%= actividad.radio_button :gym, 'No', :checked => true%>No
      </div>
      <div class="col-3">
        <%= actividad.radio_button :gym,'Si'%>Si
      </div>
    </div>
  </div>
  <div class="actions">
    <%= actividad.submit "Guardar datos", class: "btn btn-primary" %>
  </div>
<% end %>

app/views/actividades/edit.html.erb
<h1>Editar Actividad Fisica</h1>
<%= render 'form', actividad: @actividad, url: update_actividad_path %>
<%= link_to 'Regresar', index_actividad_path(params[:paciente_id]), class: 'btn btn-primary' %>

app/views/actividades/index.html.erb
<% paciente = Paciente.find(params[:paciente_id])
   @persona = paciente.personas.last
%>
<p>Nombre del Paciente: <%=  @persona.full_name%> </p>
<hr>
<div class="col-md-6">
  <% @actividades.each do |actividad| %>
    <table class="table table-bordered">
      <tr>
        <th>Practica algun deporte? </th>
        <td><%= actividad.deporte%></td>
      </tr>
      <tr>
        <th>Descripcion </th>
        <td><%= actividad.descripcion%></td>
      </tr>
      <tr>
        <th>Cuantos dias a la semana practica?</th>
        <td><%= actividad.frecuencia%></td>
      </tr>
      <tr>
        <th>Cuantas horas al dia?</th>
        <td><%= actividad.duracion%></td>
      </tr>
      <tr>
        <th>Tiempo de practica </th>
        <td><%= actividad.tiempo_practica%></td>
      </tr>
      <tr>
        <th>Actividad solo o en grupo? </th>
        <td><%= actividad.grupo_solitario%></td>
      </tr>
      <tr>
        <th>Parte de un equipo? </th>
        <td><%= actividad.equipo_amateur%></td>
      </tr>
      <tr>
        <th>Asiste al gimnasio: </th>
        <td><%= actividad.gym%></td>
      </tr>
      <tr>
        <th>Fecha de Registro</th>
        <td><%= actividad.created_at.strftime("%Y-%m-%d")%></td>
      </tr>
      <tr>
        <th>Fecha de Modificacion</th>
        <td><%= actividad.updated_at.strftime("%Y-%m-%d")%></td>
      </tr>
      <tr>
        <th><%= link_to 'Modificar', edit_actividad_path(actividad.id, paciente_id: actividad.paciente_id), class: 'btn btn-primary' %></th>
      </tr>
      <tr>
        <th><%= link_to 'Eliminar', eliminar_actividad_path(actividad.id,paciente_id: actividad.paciente_id), method: :delete, data: { confirm: 'Estas Seguro'}, class: 'btn btn-danger' %></th>
      </tr>
    </table>
    <hr>
  <% end %>
</div>
<% #TODO Se desactiva el boton %>
<% if @actividades.count < 1 %>
  <%= link_to 'Agregar Registro', new_actividad_path(params[:paciente_id]), class: 'btn btn-primary' %>
<% end %>
<%= link_to "Volver", mostrar_paciente_path(@persona.id) , class: 'btn btn-success'%>

app/views/actividades/new.html.erb
<h1>Registro de Actividad fisica del paciente</h1>
<%= render 'form', actividad: @actividad, url: create_actividad_path %>
<%= link_to 'Regresar', index_actividad_path(params[:paciente_id]), class: 'btn btn-info' %>