config/routes.rb
Rails.application.routes.draw do

  resources :consultas
  resources :consultas, except: [:index, :new] do
    resources :signos
    resources :problemas
  end


  match 'consulta/paciente/:paciente_id/index' => 'consultas#index', via: :get, :as => :consulta_index
  match 'consulta/paciente/:paciente_id/new' => 'consultas#new', via: :get, :as => :nueva_consulta
  resources :personas
  resources :alimentos
  resources :suplementos
  resources :pacientes, only: [:index, :new, :create]

  #ruta no acccesible
  match 'pacientes/:id/editar' => 'pacientes#edit', via: :get, :as => :editar_paciente
  match 'pacientes/:id/update' => 'pacientes#update', via: :patch, :as => :update_paciente
  match 'pacientes/:id/eliminar' => 'pacientes#destroy', via: :delete, :as => :eliminar_paciente
  match 'pacientes/:id' => 'pacientes#show', via: :get, :as => :mostrar_paciente

  #quimicas
  match 'paciente/:paciente_id/quimica/new' => 'quimicas#new', via: :get, :as => :new_quimica
  match 'quimicas/create' => 'quimicas#create', via: :post, :as => :create_quimica
  match 'quimicas/:id/update' => 'quimicas#update', via: :patch, :as => :update_quimica
  match 'quimicas/:id/edit' => 'quimicas#edit', via: :get, :as => :edit_quimica
  match 'paciente/:paciente_id/quimicas/index' => 'quimicas#index', via: :get, :as => :index_quimica
  match 'quimica/:id/delete' => 'quimicas#destroy', via: :delete, :as => :eliminar_quimica

  #biometrias
  match 'paciente/:paciente_id/biometria/new' => 'biometrias#new', via: :get, :as => :new_biometria
  match 'biometrias/create' => 'biometrias#create', via: :post, :as => :create_biometria
  match 'biometrias/:id/update' => 'biometrias#update', via: :patch, :as => :update_biometria
  match 'biometrias/:id/edit' => 'biometrias#edit', via: :get, :as => :edit_biometria
  match 'paciente/:paciente_id/biometrias/index' => 'biometrias#index', via: :get, :as => :index_biometria
  match 'biometria/:id/delete' => 'biometrias#destroy', via: :delete, :as => :eliminar_biometria

  #actividades
  match 'paciente/:paciente_id/actividad/new' => 'actividades#new', via: :get, :as => :new_actividad
  match 'actividades/create' => 'actividades#create', via: :post, :as => :create_actividad
  match 'actividades/:id/update' => 'actividades#update', via: :patch, :as => :update_actividad
  match 'actividades/:id/edit' => 'actividades#edit', via: :get, :as => :edit_actividad
  match 'paciente/:paciente_id/actividades/index' => 'actividades#index', via: :get, :as => :index_actividad
  match 'actividad/:id/delete' => 'actividades#destroy', via: :delete, :as => :eliminar_actividad

  #habitos
  match 'paciente/:paciente_id/habitos/new' => 'habitos#new', via: :get, :as => :new_habito
  match 'habitos/create' => 'habitos#create', via: :post, :as => :create_habito
  match 'habitos/:id/update' => 'habitos#update', via: :patch, :as => :update_habito
  match 'habitos/:id/edit' => 'habitos#edit', via: :get, :as => :edit_habito
  match 'paciente/:paciente_id/habitos/index' => 'habitos#index', via: :get, :as => :index_habito
  match 'habito/:id/delete' => 'habitos#destroy', via: :delete, :as => :eliminar_habito

  #antecedentes Clinicos
  match 'paciente/:paciente_id/antecedente/new' => 'antecedentes#new', via: :get, :as => :new_antecedente
  match 'antecedente/create' => 'antecedentes#create', via: :post, :as => :create_antecedente
  match 'antecedente/:id/update' => 'antecedentes#update', via: :patch, :as => :update_antecendete
  match 'antecedente/:id/edit' => 'antecedentes#edit', via: :get, :as => :edit_antecedente
  match 'paciente/:paciente_id/antecedentes/index' => 'antecedentes#index', via: :get, :as => :index_antecedente
  match 'antecedente/:id/delete' => 'antecedentes#destroy', via: :delete, :as => :eliminar_antecedente

  #plan de suplementos
  match 'paciente/:paciente_id/plan_suplementos/new' => 'plansuplementos#new', via: :get, :as => :new_plan
  match 'plan_suplemento/create' => 'plansuplementos#create', via: :post, :as => :create_plan
  match 'plan_suplemento/:id/update' => 'plansuplementos#update', via: :patch, :as => :update_plan
  match 'plan_suplemento/:id/edit' => 'plansuplementos#edit', via: :get, :as => :edit_plan
  match 'paciente/:paciente_id/plan_suplementos/index' => 'plansuplementos#index', via: :get, :as => :index_plan
  match 'plan_suplemento/:id/delete' => 'plansuplementos#destroy', via: :delete, :as => :eliminar_plan

  #dietas
  match 'paciente/:paciente_id/dieta/new' => 'dietas#new', via: :get, :as => :new_dieta
  match 'dieta/create' => 'dietas#create', via: :post, :as => :create_dieta
  match 'dieta/:id/update' => 'dietas#update', via: :patch, :as => :update_dieta
  match 'dieta/:id/edit' => 'dietas#edit', via: :get, :as => :edit_dieta
  match 'paciente/:paciente_id/dietas/index' => 'dietas#index', via: :get, :as => :index_dieta
  match 'dieta/:id/delete' => 'dietas#destroy', via: :delete, :as => :eliminar_dieta


  get 'nutrismart/home'


  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  match 'registrar/nutriologo', to: 'home#registro', via: :post, :as  => :guardar_nutriologo

  get 'login', to: 'sessions#new'
  match 'login' => 'sessions#create', via: :post
  delete 'logout', to: 'sessions#destroy'
  match 'register' => 'sessions#register', via: :get, :as => :registrar_nutriologo

  match 'home/index' => 'home#index', via:  :get, :as => :home_path


  root :to => 'sessions#new'
end

app/models/biometria.rb
class Biometria < ApplicationRecord
  belongs_to :paciente
end

app/controllers/biometrias_controller.rb
class BiometriasController < ApplicationController
  before_action :set_biometria, only: [:show, :edit, :update, :destroy]

  # GET /biometrias
  # GET /biometrias.json
  def index
    set_persona_biometria
  end

  # GET /biometrias/1
  # GET /biometrias/1.json
  def show
    set_persona_biometria
  end

  # GET /biometrias/new
  def new
    @biometria = Biometria.new
    @paciente = Paciente.find(params[:paciente_id])
  end

  # GET /biometrias/1/edit
  def edit
  end

  # POST /biometrias
  # POST /biometrias.json
  def create
    @biometria = Biometria.new(biometria_params)

    respond_to do |format|
      if @biometria.save
        format.html { redirect_to index_biometria_path(params[:biometria][:paciente_id]), notice: 'Datos de biometria guardados correctamente'}
        format.json { render :show, status: :created, location: @biometria }
      else
        format.html { render :new }
        format.json { render json: @biometria.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /biometrias/1
  # PATCH/PUT /biometrias/1.json
  def update
    respond_to do |format|
      if @biometria.update(biometria_params)
        format.html { redirect_to index_biometria_path(params[:biometria][:paciente_id]), notice: 'Biometria se actualizo correctamente'}
        format.json { render :show, status: :ok, location: @biometria }
      else
        format.html { render :edit }
        format.json { render json: @biometria.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /biometrias/1
  # DELETE /biometrias/1.json
  def destroy
    @biometria.destroy
    respond_to do |format|
      format.html { redirect_to index_biometria_path(params[:paciente_id]), notice: 'Biometria elimino correctamente.' }
      format.json { head :no_content }
    end
  end

  private

  def set_persona_biometria
    paciente = Paciente.find(params[:paciente_id])
    @persona = paciente.personas.last
    @biometrias = Biometria.where(paciente_id: params[:paciente_id])
  end

  # Use callbacks to share common setup or constraints between actions.
    def set_biometria
      @biometria = Biometria.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def biometria_params
      params.require(:biometria).permit(:paciente_id, :globulos_rojos,:globulos_blancos, :plaquetas, :hemoglobina, :hematocritos, :neutrofilos, :monocitos, :linfocitos)
    end
end

app/helpers/biometrias_helper.rb
module BiometriasHelper
end

app/views/biometrias/_form.html.erb
<%= form_with(model: biometria, id: 'formulario_biometria', url: url, local: true) do |biometria|%>
  <%= biometria.hidden_field(:paciente_id, :value => params[:paciente_id]) %>
  <div class="form-group">
    <%= biometria.label "Globulos Rojos" %><br>
    <%= biometria.number_field :globulos_rojos%>
  </div>
  <div class="form-group">
    <%= biometria.label "Globulos Blancos" %><br>
    <%= biometria.number_field :globulos_blancos%>
  </div>
  <div class="form-group">
    <%= biometria.label "Plaquetas" %><br>
    <%= biometria.number_field :plaquetas %>
  </div>
  <div class="form-group">
    <%= biometria.label "Hemoglobina" %><br>
    <%= biometria.number_field :hemoglobina %>
  </div>
  <div class="form-group">
    <%= biometria.label "Hematocritos"%><br>
    <%= biometria.number_field :hematocritos %>
  </div>
  <div class="form-group">
    <%= biometria.label "Neutrofilos" %><br>
    <%= biometria.number_field :neutrofilos%>
  </div>
  <div class="form-group">
    <%= biometria.label "Monocitos" %><br>
    <%= biometria.number_field :monocitos%>
  </div>
  <div class="form-group">
    <%= biometria.label "Linfocitos" %><br>
    <%= biometria.number_field :linfocitos%>
  </div>
  <div class="actions">
    <%= biometria.submit "Guardar datos", class: "btn btn-primary" %>
  </div>
<% end %>

app/views/biometrias/edit.html.erb
<h1>Editar Biometria Hematica</h1>
<%= render 'form', biometria: @biometria, url: update_biometria_path %>
<%= link_to 'Regresar', index_biometria_path(params[:paciente_id]), class: 'btn btn-primary' %>

app/views/biometrias/index.html.erb
<% paciente = Paciente.find(params[:paciente_id])
   @persona = paciente.personas.last
%>
<p>Nombre del Paciente: <%=  @persona.full_name%> </p>
<hr>
<% @biometrias.each do |biometria| %>
  <table>
    <tr>
      <th>Globulos Rojos</th>
      <td><%= biometria.globulos_rojos %></td>
    </tr>
    <tr>
      <th>Globus Blancos</th>
      <td><%= biometria.globulos_blancos%></td>
    </tr>
    <tr>
      <th>Plaquetas</th>
      <td><%= biometria.plaquetas%></td>
    </tr>
    <tr>
      <th>Hemoglobina</th>
      <td><%= biometria.hemoglobina%></td>
    </tr>
    <tr>
      <th>Hematocritos</th>
      <td><%= biometria.hematocritos%></td>
    </tr>
    <tr>
      <th>Neutrofilos</th>
      <td><%= biometria.neutrofilos%></td>
    </tr>
    <tr>
      <th>Monocitos</th>
      <td><%= biometria.monocitos%></td>
    </tr>
    <tr>
      <th>Linfocitos</th>
      <td><%= biometria.linfocitos%></td>
    </tr>
    <tr>
      <th>Fecha de Registro</th>
      <td><%= biometria.created_at.strftime("%Y-%m-%d")%></td>
    </tr>
    <tr>
      <th><%= link_to 'Modificar', edit_biometria_path(biometria.id, paciente_id: biometria.paciente_id), class: 'btn btn-primary' %></th>
    </tr>
    <tr>
      <th><%= link_to 'Eliminar', eliminar_biometria_path(biometria.id,paciente_id: biometria.paciente_id), method: :delete, data: { confirm: 'Estas Seguro'}, class: 'btn btn-danger' %></th>
    </tr>
  </table>
  <hr>
<% end %>
<%= link_to 'Agregar Registro', new_biometria_path(params[:paciente_id]), class: 'btn btn-primary' %>
<%= link_to "Volver", mostrar_paciente_path(@persona.id) , class: 'btn btn-success'%>

app/views/biometrias/new.html.erb
<h1>Registro de Biometria Ematica</h1>
<%= render 'form', biometria: @biometria , url: create_biometria_path%>
<%= link_to 'Regresar', index_biometria_path(params[:paciente_id]), class: 'btn btn-info' %>